import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { Toaster } from 'react-hot-toast';
import 'react-photo-view/dist/react-photo-view.css';
import AuthProvider from '@/provider/AuthProvider';
import Navbar from '@/components/navbar/Navbar';
import Footer from '@/components/footer/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'P-Blog-Bangladesh',
  description: 'Generated by P-Blog-Bangladesh',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <Navbar />
          <section className='max-w-[85rem] mx-auto px-4 min-h-[calc(100vh-8.8rem)]'>
            {children}
          </section>
          <Footer />
          <Toaster />
        </body>
      </AuthProvider>
    </html>
  )
}
